# -*- coding: utf-8 -*-
"""309704028_HW1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FhJ9izN7XoNm5rVyi2IMkfsNjGe0SSJA

# 1
"""

X = [['a', 'b', 'c'], 
     ('a', 'b', 'c'), 
     {1:'a', 2:'b', 3:'c'}, 
     {'a', 'b', 'c'}]
for x in X:
    print(f'{x} is a {type(x)}')

"""# 2"""

print(f'The area of the circle with radius 10 is {3.1415*10**2:.2f}!')

"""# 3"""

file = 'abc.jpg'
JPG = file.split('.')[1]
print(f'The extension of the file is: {JPG}')

"""# 4"""

A, B = {'N','C','T','U'}, {'N','Y','C','U'}
print(A.intersection(B))

"""# 5"""

from collections import Counter


participant = 'M M F M F M M M M M F F M M M F M M M'
c = Counter(participant)
n_males, n_females = c.get('M'), c.get('F')
n_total = n_males + n_females

print(f'Number of Male: {n_males} ' + f'{"*"*n_males}')
print(f'Number of Female: {n_females} ' + f'{"*"*n_females}')
print(f'Number of all participant: {n_total} ')
print(f'In groups of two, we get {n_total // 2} groups and {n_total % 2} person is left.')

"""# 6"""

new_weekdays = []
weekdays = ['SAturdAy', 'fRiday', 'tHuRSday', 'wEdnesdaY', 'TueSday', 'moNdaY', 'sUnDay']
for weekday in weekdays[::-1]:
    new_weekday = weekday.lower().capitalize()
    new_weekday = new_weekday.strip('day')
    new_weekdays.append(new_weekday)
    # print(new_weekday, end=' ')
str_ = ' '
print(str_.join(new_weekdays))

"""# 7"""

list_1 = [(2, 'c'), (1, 'a'), (4, 'b'), (2, 'e'), (2, 'd')]
list_2 = [(2, 'f'), (1, 'g')]

new_list = []
for ls in list_1:
    
    value, string = ls

    # step 1
    if string == 'b':
        value = 5
    
    # step 2
    if string == 'd':
        break
    
    
    new_list.append((value, string))
    
# step 3
new_list = new_list + list_2

# step 4
print(sorted(new_list, key=lambda x:x[1], reverse=True))

"""# 8"""

phonebook = {'NCTU': '03 571 2121', 
             'NTHU': '03 571 5131', 
             'NCCU': '02 29393091', 
             'NCKU': '06 275 7575', 
             'NTU': '02 3366 5022'}
phonebook['NYCU'] = phonebook.pop('NCTU')
for key, item in phonebook.items():
    print(f'The phone number of {key} is {item}')